version: '3'

services:
  db:
    build:
      context: .
    restart: always
    image: postgres:conference-db
    environment:
      POSTGRES_PASSWORD: 'Admin@SamGmbH1!'
    ports:
      - '5444:5432'
    volumes:
      - pgdata_db:/var/lib/postgresql/data

volumes:
  pgdata_db:
    driver: local
