version: '3'

services:
  postgres:
    restart: always
    image: postgres:conference-app
    environment:
      POSTGRES_PASSWORD: 'Admin@SamGmbH1!'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
